FROM python:alpine3.7
COPY . /app
WORKDIR /app
ENV POSTGRES_ENV = 'prod'
RUN yum install python34
RUN yum install python3-pip
RUN pip3 install flask 
RUN pip3 install psycopg2-binary	
RUN pip3 install flask-sqlalchemy	
EXPOSE 5000
CMD python3 app.py

